# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

any_inf <- function(x) {
    .Call('_cutpointr_any_inf', PACKAGE = 'cutpointr', x)
}

get_rev_dups <- function(x) {
    .Call('_cutpointr_get_rev_dups', PACKAGE = 'cutpointr', x)
}

is_equal_cpp_char <- function(x, y) {
    .Call('_cutpointr_is_equal_cpp_char', PACKAGE = 'cutpointr', x, y)
}

is_equal_cpp_num <- function(x, y) {
    .Call('_cutpointr_is_equal_cpp_num', PACKAGE = 'cutpointr', x, y)
}

one_unique_num <- function(x) {
    .Call('_cutpointr_one_unique_num', PACKAGE = 'cutpointr', x)
}

one_unique_char <- function(x) {
    .Call('_cutpointr_one_unique_char', PACKAGE = 'cutpointr', x)
}

which_are_num <- function(x, a) {
    .Call('_cutpointr_which_are_num', PACKAGE = 'cutpointr', x, a)
}

which_are_char <- function(x, a) {
    .Call('_cutpointr_which_are_char', PACKAGE = 'cutpointr', x, a)
}

